### ISSUE TITLE
Windows Defender won't let `sheret.exe` run

### ISSUE THREAD

**Issue by rotoglup** [ethanpil/sheret#2]
It is identified as threat : `Trojan:Win32/Bitrep.C`

**Comment by ethanpil** [comment]
This is most likely to the UPX compression. If you recompile from source without UPX it will not have any false positive.

**Comment by ethanpil** [comment]
Thanks for your patience. This has been addressed with the 1.1 release here: https://github.com/ethanpil/sheret/releases/tag/1.1
