### ISSUE TITLE
Cannot download Windows binary

### ISSUE THREAD

**Issue by thdoan** [ethanpil/sheret#6]
When I click on sheret-v1.21.zip, I get this popup:

![image](https://user-images.githubusercontent.com/4110567/101071785-ec6b2500-3551-11eb-9c17-427689c217f0.png)

No matter what I do, it says access denied. Is there another way to download the zip?

**Comment by ethanpil** [comment]
These release binaries are hosted on GitHub not amazon S3. 

I am not sure what is happening for you, but its either a network issue/github issue/your computer issue... On my end it downloaded just fine on two different computers connected to two different networks, plus my mobile phone.

Perhaps something temporary, please try again in a few hours.
